services:
  flask:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: flask
    restart: always
    expose:
      - 8080
    volumes:
      - ./databases:/app/databases

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
     - "80:80"