name: CD

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'add_CI_CD_branch'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy_environment
    steps:
      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> ${GITHUB_OUTPUT}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/foreverjun/se_spbu_website
          tags: |
            latest
            type=semver,pattern={{version}}
            type=raw,value=${{steps.date.outputs.date}},enable=true
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}