name: CD
#on:
on: [push, pull_request]
#  pull_request:
#    types:
#      - closed
jobs:
  deploy:
#    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'deploy')) && (github.event.pull_request.base.ref == 'test_CI_CD_branch')}}
    runs-on: ubuntu-latest
    environment: deploy_environment
    steps:
      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%d-%m-%Y')" >> ${GITHUB_OUTPUT}
          echo "date=$(date +'%d-%m-%Y')"
          echo "${{steps.date.output.date}}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/foreverjun/se_spbu_website
          tags: |
            type=raw,value=latest,enable=true
            type=raw,value=${{steps.date.output.date}},enable=true
            type=sha

#      - name: Build and push Docker image
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}


